export const DEFAULT_TOKEN_BALANCE_REFETCH_INTERVAL = 15000
export const DEFAULT_REFETCH_ON_WINDOW_FOCUS_STALE_TIME = 60000 // 1 minute
export const SECONDS_IN_A_DAY = 24 * 60 * 60;
export const MAX_DECIMALS_PRECISION = 10;